name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test and MongoDB setup
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name mongodb

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        run: npm run start:mongodb &

      - name: Run server.js
        run: npm run start:server

      - name: Run tests
        run: npm test
