name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      # Install and run MongoDB
      - name: Set up MongoDB
        uses: mongodb/setup-mongodb@v1
        with:
          mongodb-version: "4.4"

      # Start MongoDB service
      - name: Start MongoDB
        run: sudo service mongod start

      # Run server.js in the background
      - name: Start server
        run: node server.js &

      # Wait for MongoDB and server to start
      - name: Wait for server and MongoDB to start
        run: sleep 10s

      # Run tests
      - run: npm test
